name: lint-build-test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install CMake
        uses: lukka/get-cmake@v3.21.2
      - name: Setup vcpkg for dependencies
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 53bef8994c541b6561884a8395ea35715ece75db 
      - name: Build and Test
        uses: lukka/run-cmake@v10
        with: 
          configurePreset: ubuntu-runner-config
          buildPreset: ubuntu-runner-debug
          testPreset: ubuntu-runner-test
      - name: clang-format
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '14'
          check-path: './'
      - name: Linter
        working-directory: ./build/ubuntu-runner-config
        run: run-clang-tidy
