name: lint-build-test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    env:
      CMAKE_CXX_CLANG_TIDY: clang-tidy
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install CMake
        uses: lukka/get-cmake@v3.21.2
      - name: Setup vcpkg for dependencies
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 53bef8994c541b6561884a8395ea35715ece75db 
      - name: Build Lint Test
        uses: lukka/run-cmake@v10
        with: 
          configurePreset: ubuntu-runner-config
          buildPreset: ubuntu-runner-debug
          testPreset: ubuntu-runner-test
      
