name: run-tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install CMake
        uses: lukka/get-cmake@v3.25.2
      - name: Install Project Dependencies
        run: sudo apt install -y gtest sdl2 sdl2-image
      - name: Create directory for build
        run: mkdir build
      - name: Create build files
        working-directory: ./build
        run: cmake ..
      - name: Build project
        working-directory: ./build 
        run: make
      - name: Run tests
        working-directory: ./build 
        run: ctest

      
