name: run-tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install CMake
        uses: lukka/get-cmake@v3.25.2
      - name: Create build files
        run: cmake .
      - name: Build project
        run: make
      - name: Run tests
        run: ctest

      